using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using CAD;
using DTO;
using System.Data;
namespace RETO2APP.VIEWS
{
    public partial class Registrocliente : Window
    {
        public Registrocliente()
        {
            InitializeComponent();
        }
        //crear clientes
        private void Createclient(object sender, RoutedEventArgs e)
        {
            if (String.IsNullOrEmpty(txtDocumento.Text) ||
                String.IsNullOrEmpty(txtNombres.Text) ||
                String.IsNullOrEmpty(txtApellidos.Text) ||
                String.IsNullOrEmpty(txtContraseña.Text) ||
                String.IsNullOrEmpty(txtTelefono.Text))
            {
                MessageBox.Show("Por favor, complete todos los campos");
            }
            else
            {
                int filas = 0;
                CADUsuario con = new CADUsuario();
                Usuario u = new Usuario();
                u.documento = txtDocumento.Text;
                u.nombres = txtNombres.Text;
                u.apellidos = txtApellidos.Text;
                u.contraseña = txtContraseña.Text;
                u.telefono = txtTelefono.Text;
                filas = con.registrousuario(u);
                if (filas == 1)
                {
                    MessageBox.Show("Cliente registrado");
                    clearCampos();
                }
                if (filas == -2)
                {
                    MessageBox.Show("Ya hay un usuario registrado con este documento");
                }
                if (filas == 0)
                {
                    MessageBox.Show("Cliente no registrado");
                }
            }
        }
        //Ver todos los clientes registrados
        private void SearchAll(object sender, RoutedEventArgs e)
        {
            CADUsuario con = new CADUsuario();
            DataTable dt = new DataTable();
            dt = con.searchAllUsers();
            if (dt.Rows.Count > 0)
            {
                Listarusers.DataContext = dt.DefaultView;
            }
        }
        //Generar columnas de usuarios
        private void Listarusers_AutoGeneratedColumns(object sender, EventArgs e)
        {
            if (Listarusers.Columns.Count > 0)
            {
                Listarusers.Columns[0].Header = "Documento";
                Listarusers.Columns[1].Header = "Nombres";
                Listarusers.Columns[2].Header = "Apellidos";
                Listarusers.Columns[3].Header = "Contraseña";
                Listarusers.Columns[4].Header = "Telefono";
                Listarusers.Columns[5].Header = "Puntos";
            }
        }
        //Buscar un registro
        private void buscarxDoc(object sender, RoutedEventArgs e)
        {
            if (String.IsNullOrEmpty(txtDocumento.Text))
            {
                MessageBox.Show("Ingrese documento para buscar Cliente");
            }
            else
            {
                DataTable dt = new DataTable();
                CADUsuario con = new CADUsuario();
                Usuario u = new Usuario();
                u.documento = txtDocumento.Text;
                dt = con.searchxDoc(u);
                if (dt.Rows.Count > 0)
                {
                    disableTextBox();
                    txtNombres.Text = dt.Rows[0][2].ToString();
                    txtApellidos.Text = dt.Rows[0][3].ToString();
                    txtContraseña.Text = dt.Rows[0][4].ToString();
                    txtTelefono.Text = dt.Rows[0][5].ToString();
                }

            }
        }
        //Actualizar cliente
        private void Updatecliente(object sender, RoutedEventArgs e)
        {
            if (String.IsNullOrEmpty(txtTelefono.Text)||
                String.IsNullOrEmpty(txtContraseña.Text))
            {
                MessageBox.Show("No se permiten campos vacios");
            }
            else
            {
                int filas = 0;
                Usuario u = new Usuario();
                CADUsuario con = new CADUsuario();
                u.documento = txtDocumento.Text;
                u.telefono = txtTelefono.Text;
                u.contraseña = txtContraseña.Text;
                filas = con.updateusuario(u);
                if (filas>0)
                {
                    MessageBox.Show("Datos actualizados correctamente");
                    clearCampos();
                    enableTextBox();
                }
                else
                {
                    MessageBox.Show("No se pudo actualizar el usuario");
                }
            }
        }
        //Eliminar cliente
        private void deletecliente(object sender, RoutedEventArgs e)
        {
            int filas = 0;
            CADUsuario con = new CADUsuario();
            Usuario u = new Usuario();
            if (String.IsNullOrEmpty(txtDocumento.Text))
            {
                MessageBox.Show("Ingrese documento");
            }
            else
            {
                u.documento = txtDocumento.Text;
                filas = con.deleteuser(u);
                if (filas>0)
                {
                    MessageBox.Show("Cliente eliminado");
                    clearCampos();
                    enableTextBox();
                }else
                {
                    MessageBox.Show("Cliente no eliminado");
                }
            }
        }
        //back
        private void back(object sender, RoutedEventArgs e)
        {
            PanelUsers back = new PanelUsers();
            App.Current.MainWindow = back;
            back.Show();
            this.Close();
        }
        //----!Control de campos!//
        public void disableTextBox()
        {
            txtDocumento.IsEnabled = false;
            txtNombres.IsEnabled = false;
            txtApellidos.IsEnabled = false;
        }
        public void enableTextBox()
        {
            txtDocumento.IsEnabled = true;
            txtNombres.IsEnabled = true;
            txtApellidos.IsEnabled = true;
        }
        //Limpiar formulario 
        public void clearCampos()
        {
            txtNombres.Text = null;
            txtDocumento.Text = null;
            txtTelefono.Text = null;
            txtContraseña.Text = null;
            txtApellidos.Text = null;
        }
    }
}
